FUNDAMENTAL_RELATIONSHIP_MAPPINGS = [
    # Canada: energy and resource exports
    {
        "commodity": "Brent Oil",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Crude Oil / Brent",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Crude Oil",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Crude Oil / Brent",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Natural Gas",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Natural Gas / LNG",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "LNG",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Natural Gas / LNG",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Heating Oil",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Heating Oil",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Gasoline",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Gasoline",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Uranium",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Uranium",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Lumber",
        "currency": "CAD",
        "trade_country": "CAN",
        "trade_commodity": "Lumber",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },

    # Australia: resource exports
    {
        "commodity": "LNG",
        "currency": "AUD",
        "trade_country": "AUS",
        "trade_commodity": "Natural Gas / LNG",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Coal",
        "currency": "AUD",
        "trade_country": "AUS",
        "trade_commodity": "Coal",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Iron Ore",
        "currency": "AUD",
        "trade_country": "AUS",
        "trade_commodity": "Iron Ore",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Gold",
        "currency": "AUD",
        "trade_country": "AUS",
        "trade_commodity": "Gold",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Lithium",
        "currency": "AUD",
        "trade_country": "AUS",
        "trade_commodity": "Lithium",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Lithium Hydroxide",
        "currency": "AUD",
        "trade_country": "AUS",
        "trade_commodity": "Lithium",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Cattle",
        "currency": "AUD",
        "trade_country": "AUS",
        "trade_commodity": "Cattle",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },

    # China copper demand as an AUD macro driver
    {
        "commodity": "Copper",
        "currency": "AUD",
        "trade_country": "CHN",
        "trade_commodity": "Copper",
        "flow_metric": "imports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "china_import_demand",
    },

    # Brazil: commodity exports
    {
        "commodity": "Iron Ore",
        "currency": "BRL",
        "trade_country": "BRA",
        "trade_commodity": "Iron Ore",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Soybeans",
        "currency": "BRL",
        "trade_country": "BRA",
        "trade_commodity": "Soybeans",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Corn",
        "currency": "BRL",
        "trade_country": "BRA",
        "trade_commodity": "Corn",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Sugar",
        "currency": "BRL",
        "trade_country": "BRA",
        "trade_commodity": "Sugar",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
    {
        "commodity": "Coffee",
        "currency": "BRL",
        "trade_country": "BRA",
        "trade_commodity": "Coffee",
        "flow_metric": "exports_usd",
        "fundamental_sign": 1,
        "fundamental_role": "export_strength",
    },
]