COMMODITY_MARKET_SYMBOLS = {
    "Brent Oil": "NYMEX:BZ1!",
    "Crude Oil": "NYMEX:CL1!",
    "Natural Gas": "NYMEX:NG1!",
    "Gasoline": "NYMEX:RB1!",
    "Coal": "ICEEUR:NCF1!",
    "Uranium": "FX:Uranium",
    "Gold": "COMEX:GC1!",
    "Silver": "COMEX:SI1!",
    "Iron Ore": "SGX:FEF1!",
    "Copper": "COMEX:HG1!",
    "Aluminum": "COMEX:ALI1!",
    "Zinc": "RUS:ZC1!",
    "Nickel": "RUS:NC1!",
    "Platinum": "NYMEX:PL1!",
    "Palladium": "NYMEX:PA1!",
    "Soybeans": "CBOT:ZS1!",
    "Wheat": "CBOT:ZW1!",
    "Corn": "CBOT:ZC1!",
    "Sugar": "ICEUS:SB1!",
    "Coffee": "ICEUS:KC1!",
    "Cotton": "ICEUS:CT1!",
    "Cocoa": "ICEUS:CC1!",
    "Cattle": "CME:LE1!",
    "Lithium": "AMEX:LIT",
    "Lumber": "CME:LBR1!",
    "Heating Oil": "NYMEX:HO1!",
    "LNG": "ABAXX:GOM1!",
    "Lithium Hydroxide": "COMEX:LTH1!",
}


DIRECT_FX_SYMBOLS = {
    "FX:EURUSD",
    "FX:GBPUSD",
    "FX:NZDUSD",
    "FX:AUDUSD",
    "FX:EURGBP",
    "FX:EURJPY",
    "FX:EURCHF",
    "FX:EURCAD",
    "FX:EURAUD",
    "FX:EURNZD",
    "FX:GBPJPY",
    "FX:GBPCHF",
    "FX:GBPCAD",
    "FX:GBPAUD",
    "FX:GBPNZD",
    "FX:AUDJPY",
    "FX:AUDNZD",
    "FX:AUDCAD",
    "FX:NZDJPY",
    "FX:NZDCAD",
    "FX:CADJPY",
    "FX:CHFJPY",
    "FX:USDJPY",
    "FX:USDCHF",
    "FX:USDCAD",
    "FX_IDC:BRLUSD",
}


DERIVED_FX_SYMBOLS = {
    "DERIVED:CADUSD",
    "DERIVED:CHFUSD",
    "DERIVED:JPYUSD",
    "DERIVED:USDBRL",
}


VALID_FX_SYMBOLS = DIRECT_FX_SYMBOLS | DERIVED_FX_SYMBOLS